sudo: required
services:
    - docker
env:
    global:
        - GIT_SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
        # Above removes the user prompt "Are you sure?" from the Google gcloud CLI
before_install:
    - openssl aes-256-cbc -K $encrypted_ef59ff332771_key -iv $encrypted_ef59ff332771_iv -in google_iam_service_account_creds.json.enc -out google_iam_service_account_creds.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file google_iam_service_account_creds.json
    - gcloud config set project k8s-react-multicontainer
    - gcloud config set compute/zone asia-south1-a
    - gcloud container clusters get-credentials k8s--react-multicontainer-cluster
    - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker build -t sunnymishra0389/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true sunnymishra0389/react-test npm test
    
# Unlike previous Project where Travis file itself contained the script to Build+Deploy Image in provider:elasticbeanstalk, the Travis doesn't support Kubernetes deployment out of the box, so we have to write all that out manually in our own customer deploy.sh file below
deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master